// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roverToEarthBaseComm.proto

#ifndef PROTOBUF_roverToEarthBaseComm_2eproto__INCLUDED
#define PROTOBUF_roverToEarthBaseComm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "protocolEnums.pb.h"
// @@protoc_insertion_point(includes)
namespace ORION_COMM {
namespace REPLY {
class DriveModuleTelemetry;
class DriveModuleTelemetryDefaultTypeInternal;
extern DriveModuleTelemetryDefaultTypeInternal _DriveModuleTelemetry_default_instance_;
class Reply;
class ReplyDefaultTypeInternal;
extern ReplyDefaultTypeInternal _Reply_default_instance_;
class WheelTelemetry;
class WheelTelemetryDefaultTypeInternal;
extern WheelTelemetryDefaultTypeInternal _WheelTelemetry_default_instance_;
}  // namespace REPLY
}  // namespace ORION_COMM

namespace ORION_COMM {
namespace REPLY {

namespace protobuf_roverToEarthBaseComm_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_roverToEarthBaseComm_2eproto

// ===================================================================

class WheelTelemetry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ORION_COMM.REPLY.WheelTelemetry) */ {
 public:
  WheelTelemetry();
  virtual ~WheelTelemetry();

  WheelTelemetry(const WheelTelemetry& from);

  inline WheelTelemetry& operator=(const WheelTelemetry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WheelTelemetry& default_instance();

  static inline const WheelTelemetry* internal_default_instance() {
    return reinterpret_cast<const WheelTelemetry*>(
               &_WheelTelemetry_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(WheelTelemetry* other);

  // implements Message ----------------------------------------------

  inline WheelTelemetry* New() const PROTOBUF_FINAL { return New(NULL); }

  WheelTelemetry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WheelTelemetry& from);
  void MergeFrom(const WheelTelemetry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WheelTelemetry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double angularVelocity = 2;
  void clear_angularvelocity();
  static const int kAngularVelocityFieldNumber = 2;
  double angularvelocity() const;
  void set_angularvelocity(double value);

  // double current = 3;
  void clear_current();
  static const int kCurrentFieldNumber = 3;
  double current() const;
  void set_current(double value);

  // int32 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 pwm = 5;
  void clear_pwm();
  static const int kPwmFieldNumber = 5;
  ::google::protobuf::int32 pwm() const;
  void set_pwm(::google::protobuf::int32 value);

  // double heatSinkTemperature = 4;
  void clear_heatsinktemperature();
  static const int kHeatSinkTemperatureFieldNumber = 4;
  double heatsinktemperature() const;
  void set_heatsinktemperature(double value);

  // int32 errorCode = 6;
  void clear_errorcode();
  static const int kErrorCodeFieldNumber = 6;
  ::google::protobuf::int32 errorcode() const;
  void set_errorcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ORION_COMM.REPLY.WheelTelemetry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double angularvelocity_;
  double current_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 pwm_;
  double heatsinktemperature_;
  ::google::protobuf::int32 errorcode_;
  mutable int _cached_size_;
  friend struct protobuf_roverToEarthBaseComm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DriveModuleTelemetry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ORION_COMM.REPLY.DriveModuleTelemetry) */ {
 public:
  DriveModuleTelemetry();
  virtual ~DriveModuleTelemetry();

  DriveModuleTelemetry(const DriveModuleTelemetry& from);

  inline DriveModuleTelemetry& operator=(const DriveModuleTelemetry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DriveModuleTelemetry& default_instance();

  static inline const DriveModuleTelemetry* internal_default_instance() {
    return reinterpret_cast<const DriveModuleTelemetry*>(
               &_DriveModuleTelemetry_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(DriveModuleTelemetry* other);

  // implements Message ----------------------------------------------

  inline DriveModuleTelemetry* New() const PROTOBUF_FINAL { return New(NULL); }

  DriveModuleTelemetry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DriveModuleTelemetry& from);
  void MergeFrom(const DriveModuleTelemetry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DriveModuleTelemetry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ORION_COMM.REPLY.WheelTelemetry wheel = 1;
  int wheel_size() const;
  void clear_wheel();
  static const int kWheelFieldNumber = 1;
  const ::ORION_COMM::REPLY::WheelTelemetry& wheel(int index) const;
  ::ORION_COMM::REPLY::WheelTelemetry* mutable_wheel(int index);
  ::ORION_COMM::REPLY::WheelTelemetry* add_wheel();
  ::google::protobuf::RepeatedPtrField< ::ORION_COMM::REPLY::WheelTelemetry >*
      mutable_wheel();
  const ::google::protobuf::RepeatedPtrField< ::ORION_COMM::REPLY::WheelTelemetry >&
      wheel() const;

  // @@protoc_insertion_point(class_scope:ORION_COMM.REPLY.DriveModuleTelemetry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ORION_COMM::REPLY::WheelTelemetry > wheel_;
  mutable int _cached_size_;
  friend struct protobuf_roverToEarthBaseComm_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Reply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ORION_COMM.REPLY.Reply) */ {
 public:
  Reply();
  virtual ~Reply();

  Reply(const Reply& from);

  inline Reply& operator=(const Reply& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Reply& default_instance();

  enum FeedbackContentCase {
    kChassis = 3,
    FEEDBACK_CONTENT_NOT_SET = 0,
  };

  static inline const Reply* internal_default_instance() {
    return reinterpret_cast<const Reply*>(
               &_Reply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Reply* other);

  // implements Message ----------------------------------------------

  inline Reply* New() const PROTOBUF_FINAL { return New(NULL); }

  Reply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Reply& from);
  void MergeFrom(const Reply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Reply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .ORION_COMM.CMD_TYPE reply_type = 1;
  void clear_reply_type();
  static const int kReplyTypeFieldNumber = 1;
  ::ORION_COMM::CMD_TYPE reply_type() const;
  void set_reply_type(::ORION_COMM::CMD_TYPE value);

  // .ORION_COMM.MODULE module = 2;
  void clear_module();
  static const int kModuleFieldNumber = 2;
  ::ORION_COMM::MODULE module() const;
  void set_module(::ORION_COMM::MODULE value);

  // .ORION_COMM.REPLY.DriveModuleTelemetry chassis = 3;
  bool has_chassis() const;
  void clear_chassis();
  static const int kChassisFieldNumber = 3;
  const ::ORION_COMM::REPLY::DriveModuleTelemetry& chassis() const;
  ::ORION_COMM::REPLY::DriveModuleTelemetry* mutable_chassis();
  ::ORION_COMM::REPLY::DriveModuleTelemetry* release_chassis();
  void set_allocated_chassis(::ORION_COMM::REPLY::DriveModuleTelemetry* chassis);

  FeedbackContentCase feedback_content_case() const;
  // @@protoc_insertion_point(class_scope:ORION_COMM.REPLY.Reply)
 private:
  void set_has_chassis();

  inline bool has_feedback_content() const;
  void clear_feedback_content();
  inline void clear_has_feedback_content();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int reply_type_;
  int module_;
  union FeedbackContentUnion {
    FeedbackContentUnion() {}
    ::ORION_COMM::REPLY::DriveModuleTelemetry* chassis_;
  } feedback_content_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct protobuf_roverToEarthBaseComm_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// WheelTelemetry

// int32 ID = 1;
inline void WheelTelemetry::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 WheelTelemetry::id() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.WheelTelemetry.ID)
  return id_;
}
inline void WheelTelemetry::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.WheelTelemetry.ID)
}

// double angularVelocity = 2;
inline void WheelTelemetry::clear_angularvelocity() {
  angularvelocity_ = 0;
}
inline double WheelTelemetry::angularvelocity() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.WheelTelemetry.angularVelocity)
  return angularvelocity_;
}
inline void WheelTelemetry::set_angularvelocity(double value) {
  
  angularvelocity_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.WheelTelemetry.angularVelocity)
}

// double current = 3;
inline void WheelTelemetry::clear_current() {
  current_ = 0;
}
inline double WheelTelemetry::current() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.WheelTelemetry.current)
  return current_;
}
inline void WheelTelemetry::set_current(double value) {
  
  current_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.WheelTelemetry.current)
}

// double heatSinkTemperature = 4;
inline void WheelTelemetry::clear_heatsinktemperature() {
  heatsinktemperature_ = 0;
}
inline double WheelTelemetry::heatsinktemperature() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.WheelTelemetry.heatSinkTemperature)
  return heatsinktemperature_;
}
inline void WheelTelemetry::set_heatsinktemperature(double value) {
  
  heatsinktemperature_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.WheelTelemetry.heatSinkTemperature)
}

// int32 pwm = 5;
inline void WheelTelemetry::clear_pwm() {
  pwm_ = 0;
}
inline ::google::protobuf::int32 WheelTelemetry::pwm() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.WheelTelemetry.pwm)
  return pwm_;
}
inline void WheelTelemetry::set_pwm(::google::protobuf::int32 value) {
  
  pwm_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.WheelTelemetry.pwm)
}

// int32 errorCode = 6;
inline void WheelTelemetry::clear_errorcode() {
  errorcode_ = 0;
}
inline ::google::protobuf::int32 WheelTelemetry::errorcode() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.WheelTelemetry.errorCode)
  return errorcode_;
}
inline void WheelTelemetry::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.WheelTelemetry.errorCode)
}

// -------------------------------------------------------------------

// DriveModuleTelemetry

// repeated .ORION_COMM.REPLY.WheelTelemetry wheel = 1;
inline int DriveModuleTelemetry::wheel_size() const {
  return wheel_.size();
}
inline void DriveModuleTelemetry::clear_wheel() {
  wheel_.Clear();
}
inline const ::ORION_COMM::REPLY::WheelTelemetry& DriveModuleTelemetry::wheel(int index) const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.DriveModuleTelemetry.wheel)
  return wheel_.Get(index);
}
inline ::ORION_COMM::REPLY::WheelTelemetry* DriveModuleTelemetry::mutable_wheel(int index) {
  // @@protoc_insertion_point(field_mutable:ORION_COMM.REPLY.DriveModuleTelemetry.wheel)
  return wheel_.Mutable(index);
}
inline ::ORION_COMM::REPLY::WheelTelemetry* DriveModuleTelemetry::add_wheel() {
  // @@protoc_insertion_point(field_add:ORION_COMM.REPLY.DriveModuleTelemetry.wheel)
  return wheel_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ORION_COMM::REPLY::WheelTelemetry >*
DriveModuleTelemetry::mutable_wheel() {
  // @@protoc_insertion_point(field_mutable_list:ORION_COMM.REPLY.DriveModuleTelemetry.wheel)
  return &wheel_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ORION_COMM::REPLY::WheelTelemetry >&
DriveModuleTelemetry::wheel() const {
  // @@protoc_insertion_point(field_list:ORION_COMM.REPLY.DriveModuleTelemetry.wheel)
  return wheel_;
}

// -------------------------------------------------------------------

// Reply

// .ORION_COMM.CMD_TYPE reply_type = 1;
inline void Reply::clear_reply_type() {
  reply_type_ = 0;
}
inline ::ORION_COMM::CMD_TYPE Reply::reply_type() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.Reply.reply_type)
  return static_cast< ::ORION_COMM::CMD_TYPE >(reply_type_);
}
inline void Reply::set_reply_type(::ORION_COMM::CMD_TYPE value) {
  
  reply_type_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.Reply.reply_type)
}

// .ORION_COMM.MODULE module = 2;
inline void Reply::clear_module() {
  module_ = 0;
}
inline ::ORION_COMM::MODULE Reply::module() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.Reply.module)
  return static_cast< ::ORION_COMM::MODULE >(module_);
}
inline void Reply::set_module(::ORION_COMM::MODULE value) {
  
  module_ = value;
  // @@protoc_insertion_point(field_set:ORION_COMM.REPLY.Reply.module)
}

// .ORION_COMM.REPLY.DriveModuleTelemetry chassis = 3;
inline bool Reply::has_chassis() const {
  return feedback_content_case() == kChassis;
}
inline void Reply::set_has_chassis() {
  _oneof_case_[0] = kChassis;
}
inline void Reply::clear_chassis() {
  if (has_chassis()) {
    delete feedback_content_.chassis_;
    clear_has_feedback_content();
  }
}
inline  const ::ORION_COMM::REPLY::DriveModuleTelemetry& Reply::chassis() const {
  // @@protoc_insertion_point(field_get:ORION_COMM.REPLY.Reply.chassis)
  return has_chassis()
      ? *feedback_content_.chassis_
      : ::ORION_COMM::REPLY::DriveModuleTelemetry::default_instance();
}
inline ::ORION_COMM::REPLY::DriveModuleTelemetry* Reply::mutable_chassis() {
  if (!has_chassis()) {
    clear_feedback_content();
    set_has_chassis();
    feedback_content_.chassis_ = new ::ORION_COMM::REPLY::DriveModuleTelemetry;
  }
  // @@protoc_insertion_point(field_mutable:ORION_COMM.REPLY.Reply.chassis)
  return feedback_content_.chassis_;
}
inline ::ORION_COMM::REPLY::DriveModuleTelemetry* Reply::release_chassis() {
  // @@protoc_insertion_point(field_release:ORION_COMM.REPLY.Reply.chassis)
  if (has_chassis()) {
    clear_has_feedback_content();
    ::ORION_COMM::REPLY::DriveModuleTelemetry* temp = feedback_content_.chassis_;
    feedback_content_.chassis_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Reply::set_allocated_chassis(::ORION_COMM::REPLY::DriveModuleTelemetry* chassis) {
  clear_feedback_content();
  if (chassis) {
    set_has_chassis();
    feedback_content_.chassis_ = chassis;
  }
  // @@protoc_insertion_point(field_set_allocated:ORION_COMM.REPLY.Reply.chassis)
}

inline bool Reply::has_feedback_content() const {
  return feedback_content_case() != FEEDBACK_CONTENT_NOT_SET;
}
inline void Reply::clear_has_feedback_content() {
  _oneof_case_[0] = FEEDBACK_CONTENT_NOT_SET;
}
inline Reply::FeedbackContentCase Reply::feedback_content_case() const {
  return Reply::FeedbackContentCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace REPLY
}  // namespace ORION_COMM

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_roverToEarthBaseComm_2eproto__INCLUDED
